### ISSUE TITLE
index.html needed

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#1]
~~An index page is needed so something appears at http://mhwkb.github.io/ insetead of a 404 error page. ;)~~

**Comment by andy5995** [comment]
Ooops.. I see that URL won't work because the first part has to match my username or organization name.

https://pages.github.com/
>If the first part of the repository doesn’t exactly match your username, it won’t work, so make sure to get it right.

I'm not sure how to correct that yet.

Maybe it would be easier to just have all the links displayed by browsing the repo, and forget about a web site.

But it seems that a program that can parse links would be better in the long-term.

Open to discussion...

**Comment by andy5995** [comment]
I renamed the repo, dropping the _.github.io_ part of it.

**Comment by SunyataZero** [comment]
@andy5995 I can help out here i think, i have some experience both with user/org sites as well as "repo sites", there are different options, you can use jekyll or another static site generator and jekyll can even be integrated for repo pages if i recall. Also it's possible to use the docs folder rather than a gh-pages branch, though this gives less flexibility. Kind Regards, Tord

**Comment by andy5995** [comment]
This issue is now covered in #6 . Closing...

Thanks @SunyataZero
